#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if [ -z `command -v git` ]; then
    echo "**** adding plex-xbmcnfotvimporter deps to package install list ****"
    echo "git" >> /mod-repo-packages-to-install.list
else
    echo "**** plex-xbmcnfotvimporter deps already installed, skipping ****"
fi
